name: sublora
channels:
  - defaults
  - conda-forge
dependencies:
  - python=3.8.17
  - pip=23.2.1
  - setuptools=68.0.0
  - pip:
      - torch==2.0.1
      - numpy==1.24.4
      - transformers==4.31.0
      - datasets==2.14.2
      - accelerate==0.21.0
      - peft==0.4.0
      - loralib==0.1.1
      - evaluate==0.4.0
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - pandas==2.0.3
      - tqdm==4.65.0
      - wandb==0.15.3
      - hydra-core==1.3.2
      - omegaconf==2.3.0
      - einops==0.6.1
      - sentencepiece==0.1.99
      - tokenizers==0.13.3
      - safetensors==0.3.1
      - huggingface-hub==0.16.4
      - requests==2.31.0
      - pyyaml==6.0.1
      - regex==2023.6.3
      - filelock==3.12.2
      - fsspec==2023.6.0
      - packaging==23.1
      - psutil==5.9.5
      - typing-extensions==4.7.1
      - sympy==1.12
      - networkx==3.1
      - jinja2==3.1.2
      - mpmath==1.3.0
      - certifi==2023.7.22
      - charset-normalizer==3.2.0
      - idna==3.4
      - urllib3==1.26.16
      - python-dateutil==2.8.2
      - pytz==2023.3
      - tzdata==2023.3
      - six==1.16.0
      - joblib==1.3.1
      - threadpoolctl==3.2.0
      - pillow==10.0.0
      - xxhash==3.3.0
      - dill==0.3.7
      - multiprocess==0.70.15
      - pyarrow==12.0.1
      - aiohttp==3.8.5
      - aiosignal==1.3.1
      - async-timeout==4.0.2
      - attrs==23.1.0
      - frozenlist==1.4.0
      - multidict==6.0.4
      - yarl==1.9.2
      - click==8.1.7
      - docker-pycreds==0.4.0
      - gitdb==4.0.10
      - gitpython==3.1.32
      - pathtools==0.1.2
      - protobuf==3.20.3
      - sentry-sdk==1.30.0
      - setproctitle==1.3.2
      - smmap==5.0.0
      - appdirs==1.4.4